# Human readable name of this type
name: Software requests

# Lowercase, underscored handle used to access this type
slug: software_requests

# Explanatory text displayed in the back-office
description: Software install requests submitted via website

# Slug of field used to identify entries by default, such as the title
label_field_name: name

# Valid values: manually, created_at, updated_at, or the slug of any field
order_by: created_at

# Valid values: asc (ascending) and desc (descending). Set to asc by default.
order_direction: desc

# Specify a field slug to group entries by that field in the back-office.
group_by: location

# Activate public 'create' API (e.g for a contact form)
public_submission_enabled: true

# Array of emails to be notified of new entries made with the public API
# -- MUST BE TIED TO LOCOMOTIVE ACCOUNTS!!!
# -- https://gitter.im/locomotivecms/engine?at=57484afea78d5a256e386b67
public_submission_accounts: ['nick.cappadona@cornell.edu']

# Control the display of the content type in the back-office.
# display_settings:
#   seo: false              # display the SEO tab for the content entries
#   advanced: false         # display the Advanced tab for the content entries
#   position: 1             # position in the sidebar menu
#   hidden: false           # hidden for authors?

# By default, the back-office displays the _label property (see label_field_name) of the content entry. This can be modified by writing your own Liquid template below:
# entry_template: '<a href="{{ link }}">{{ entry._label }}</a>' # The default template

# A list describing each field
fields:
- name: # The lowercase, underscored name of the field
    label: Name # Human readable name of the field
    type: string
    required: true
    localized: false

- email: # The lowercase, underscored name of the field
    label: Email # Human readable name of the field
    type: string
    required: true
    localized: false

- phone: # The lowercase, underscored name of the field
    label: Phone # Human readable name of the field
    type: string
    required: true
    localized: false

- department: # The lowercase, underscored name of the field
    label: Department # Human readable name of the field
    type: string
    required: true
    localized: false

- affiliation: # The lowercase, underscored name of the field
    label: Affiliation # Human readable name of the field
    type: select
    required: true
    localized: false    # if localized, use
    #   en: ['option1_en', 'option2_en']
    #   fr: ['option1_fr', 'option2_fr']
    select_options: ['Course Instructor', 'Staff', 'Student']

- course_related: # The lowercase, underscored name of the field
    label: Course related # Human readable name of the field
    type: boolean
    required: true
    localized: false

- title: # The lowercase, underscored name of the field
    label: Software Title # Human readable name of the field
    type: string
    required: true
    localized: false

- company: # The lowercase, underscored name of the field
    label: Software Company Name # Human readable name of the field
    type: string
    required: true
    localized: false

- url: # The lowercase, underscored name of the field
    label: Software Website # Human readable name of the field
    type: string
    required: true
    localized: false

- platform_managed_list: # The lowercase, underscored name of the field
    label: Manage software platforms # Human readable name of the field
    type: select
    required: false
    hint: DON'T select values! Just use EDIT OPTIONS link to manage the options presented to users
    localized: false    # if localized, use
    #   en: ['option1_en', 'option2_en']
    #   fr: ['option1_fr', 'option2_fr']
    select_options: ['Windows', 'Mac (unavailable in Mann classrooms)']

- platform: # The lowercase, underscored name of the field
    label: Requested software platforms # Human readable name of the field
    type: tags
    required: true
    hint: This field records the platforms selected by the user when submitting a request
    localized: false    # if localized, use

- licenses: # The lowercase, underscored name of the field
    label: Number of Licenses # Human readable name of the field
    type: string
    required: false
    localized: false

- date: # The lowercase, underscored name of the field
    label: Date Software Needed # Human readable name of the field
    type: date
    required: true
    localized: false

- delivery: # The lowercase, underscored name of the field
    label: Software Delivery # Human readable name of the field
    type: select
    required: true
    localized: false    # if localized, use
    #   en: ['option1_en', 'option2_en']
    #   fr: ['option1_fr', 'option2_fr']
    select_options: ['Hand deliver to Mann Library ITS - Attention: Gabriel Plaine', 'Will email license/software/instructions to mann-pac-help@cornell.edu', 'Software can be downloaded at website provided above', 'See Notes below']

- location: # The lowercase, underscored name of the field
    label: Location # Human readable name of the field
    type: select
    required: true
    localized: false    # if localized, use
    #   en: ['option1_en', 'option2_en']
    #   fr: ['option1_fr', 'option2_fr']
    select_options: ['Classroom B30A', 'Classroom B30B', 'Stone Classroom', '1st floor public computers']

- notes: # The lowercase, underscored name of the field
    label: Notes # Human readable name of the field
    type: text
    required: false
    localized: false
    # text_formatting: html # html (uses rich text editor), markdown or text (uses plain text editor)
